### ISSUE TITLE
Support dev file decryption

### ISSUE THREAD

**Issue by piegit** [koolkdev/wfs-tools#2]
wfs-extract won't work with a otp.bin from a dev console

**Comment by koolkdev** [comment]
Hey, I need some more information for checking this out.
Are you referring to CAT-DEV or CAT-R device?
Can you provider me privately a sample of otp.bin and the first 0x4000 bytes of the MLC of such console? 
Thanks.

**Comment by InternalLoss** [comment]
Very much necroposting, but I am able to provide a dump of MLC from my Wii U CAT-I Kiosk (which is basically a CAT-R but not:tm:) - would you want this via Discord or email?

**Comment by piegit** [comment]
> Hey, I need some more information for checking this out. Are you referring to CAT-DEV or CAT-R device? Can you provider me privately a sample of otp.bin and the first 0x4000 bytes of the MLC of such console? Thanks.

I'm even more of a necro poster, what's your email?
