### ISSUE TITLE
macOS arm64 builds do not work

### ISSUE THREAD

**Issue by caleb39411** [koolkdev/wfs-tools#32]
When attempting to run the arm64 prebuilt release v1.21 binaries on macOS 14.4, the following is produced
```
zsh: trace trap  /Users/caleb/Downloads/wfs-tools-v1.2.1-macos-arm64/wfs-extract
```

I was able to reproduce this by exporting the variables `LDFLAGS="-L/opt/homebrew/opt/llvm/lib"` and `CPPFLAGS="-I/opt/homebrew/opt/llvm/include"` before compiling. Without these environment variables the compiled builds ran fine.

I was also unable to compile it with gcc or AppleClang, which ought to be noted in the readme.

Here is my build: [wfs-tools.zip](https://github.com/koolkdev/wfs-tools/files/14662085/wfs-tools.zip)

**Comment by koolkdev** [comment]
Thanks for the report and reproduction.
Can you verify if the artifacts that attached here are working?
https://github.com/koolkdev/wfs-tools/actions/runs/8404738575

**Comment by caleb39411** [comment]
As far as I can tell the artefacts run perfectly well.
