### ISSUE TITLE
Error Extracting.

### ISSUE THREAD

**Issue by godreborn** [koolkdev/wfs-tools#43]
I'm getting this error: 

![image](https://github.com/koolkdev/wfs-tools/assets/13548481/7e71fe53-23a5-4e3f-912d-29c3db0d9d28)

I've always gotten errors extracting the mlc, and I have no idea why.  it simply says that a file can't be read, and this has happened across two systems.  however, the file error is different for each one, a different file can't be read.  I don't know if it's the dumper or extractor, but I ftp'd the file over, and injected it.  same error as you can see, afterwards.

**Comment by godreborn** [comment]
So it's normal?  I'm just a little concerned, because I don't know if the nand dumper dumped the nand correctly in case of needing to reflash.  Thanks for responding.

**Comment by koolkdev** [comment]
Yes it is normal. Sadly it is a known limitation with dumping/flashing back mlc. flashing it back may not work because of the scfm. the best chance is to delete it before flashing back, but in this case for example the file will remain corrupted.
