### ISSUE TITLE
Improve the build process of wfs-fuse

### ISSUE THREAD

**Issue by chasedream1129** [koolkdev/wfs-tools#5]
Improve the build process of `wfs-fuse` and release the `wfs-fuse` binary

I uncommented `# add_subdirectory(wfs-fuse)` in `CMakeLists.txt` but I still can't build `wfs-fuse`
```
ents: program_options 
CMake Error at wfs-fuse/CMakeLists.txt:21:
  Parse error.  Expected "(", got newline with text "

  ".
```

**Comment by chasedream1129** [comment]
Also, is wfs-fuse writeable?

**Comment by koolkdev** [comment]
Hey, sorry for the delayed response. 
I didn't include wfs-fuse in the new build system yet.

Right now you will have to build the version of wfs tools from before the refactor:
commit f0256259a8f396e234543e7615c42fe4836b486f @ [wfslib](https://github.com/koolkdev/wfslib)

But I will properly add it soon.

As for the GCC - it was a typo. GCC 11 is required, not 12. I am updating the readme...

**Comment by thepagan** [comment]
Ok great! Thank you for that update.  I'll use the GCC11 and pull from that commit.

**Comment by thepagan** [comment]
Confirming that system does build and is functional in Ubuntu 22.04 using GCC11 and the pre-refactor commit.
